### ISSUE TITLE
Idle timeout reached for 

### ISSUE THREAD

**Issue by cmargiotta** [koillection/koillection#1257]
Hi, thanks a lot for developing this tool!

I am having a lot of troubles while trying to use scrapers, every request I do ends in a "Idle timeout reached for ...", I tested the xpath as written in the wiki and it works, I tried to ping the web service from the running container and the connection does not have any issue. 

The scraper I am trying to use is based on openlibrary.org, but I get this error even on the examples from the wiki or using github.com as address.

I am in a docker swarm environment, this is the service I am using:
```
koillection:
        image: koillection/koillection:1.5.16
        ports:
            - 8167:80
        networks:
            - internal
        environment:
            - APP_ENV=prod
            - APP_DEBUG=0
            - DB_DRIVER=pdo_pgsql
            - DB_NAME=koillection
            - DB_HOST=postgresql
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_VERSION=15
            - PHP_TZ=Europe/Rome
            - UPLOAD_MAX_FILESIZE=50M
            - PHP_MEMORY_LIMIT=512M
            - HTTPS_ENABLED=0
        volumes:
            - /data/data/koillection:/uploads
 ```
 
 Everything else seems to work well.
 
 Thanks in advance!
