### ISSUE TITLE
Error Setting Certificate File

### ISSUE THREAD

**Issue by kojiinari** [koillection/koillection#1340]
Running Docker using the default compose / .env file provided in the documentation. I set up the my figurecollection scraper as per the example in the scraper section of the wiki, but I get the following error when trying to use it: 

Error setting certificate file: /etc/ssl/certs/ca-certificates.crt for "https://myfigurecollection.net/item/2250570".

![Image](https://github.com/user-attachments/assets/44e210ca-52b0-45d6-b5bf-da812f451134)

I did try to docker exec into the /etc/ssl/certs/ folder but it was empty. Is this some kind of persmissions issue?

**Comment by kojiinari** [comment]
I attempted to fix this by bind mounting the certificate of the host machine to the container.
 the docker-compose: 
```
services:
    # Koillection
    koillection:
        image: koillection/koillection
        container_name: koillection
        restart: unless-stopped
        ports:
            - 8062:80
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - ./volumes/koillection/uploads:/uploads
            # Added the following to try and solve certificate issues when scraping:
            - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    # Database : choose one of the following
    db:
        image: postgres:16
        container_name: db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - "./volumes/postgresql:/var/lib/postgresql/data"
```


Now the error that I get is a 403. 

![Image](https://github.com/user-attachments/assets/53d2548c-c189-4958-b2bf-6a616b43086f)

Scrape protection maybe on MFC's side?
