### ISSUE TITLE
Unable to add any additional images to a record: "There is not enough space left on your account to execute this action"

### ISSUE THREAD

**Issue by vrai** [koillection/koillection#1341]
I've been slowly populating a collection that's stored in a Koillection instance running on Docker. The `docker-compose.yml` contents are at the bottom of this message.

I've added 83 entries, most of switch have at least one populated image field, with some having up to four. In total there are 112 images attached, and the uploads directory contains 518M of data.

However, I no longer add any images. Despite the volume holding the uploads (and indeed all the mapped directories for both Koillection and Postgres) having >1.7T available. I get the error: "There is not enough space left on your account to execute this action".

Any idea what's causing this?

The `docker-compose.yml` is as follows:
```
services:
  koillection:
    image: koillection/koillection
    container_name: koillection
    restart: unless-stopped
    ports:
      - 4460:80
    environment:
      - DB_DRIVER=pdo_pgsql
      - DB_NAME=koillection
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=koillectionuser
      - DB_PASSWORD=koillectionpass
      - DB_VERSION=16
      - PHP_TZ=Europe/London
      - HTTPS_ENABLED=0
      - PUID=1026
      - PGID=100
    depends_on:
      - db
    volumes:
      - ./conf:/conf:rw
      - ./uploads:/uploads:rw
  db:
    image: postgres:16
    container_name: koillection-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "koillection", "-U", "koillectionuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_DB=koillection
      - POSTGRES_USER=koillectionuser
      - POSTGRES_PASSWORD=koillectionpass
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    restart: unless-stopped
```
