### ISSUE TITLE
HTTPS SSL certificate error

### ISSUE THREAD

**Issue by punfil** [koillection/koillection#738]
Hi!
Today I wanted to try Koillection out. I decided to install it with using docker compose. I would like to use HTTPS instead of HTTP.
My config:
```

version: '3'

services:
    # Koillection
    koillection:
        image: koillection/koillection
        container_name: koillection
        restart: unless-stopped
        ports:
          - 443:80
        environment:
            - DB_DRIVER=pdo_mysql
            - DB_NAME=koillection
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_VERSION=12.2
            - PHP_TZ=Europe/Warsaw
            - HTTPS_ENABLED=1
        depends_on:
            - db
        volumes:
            - ./docker/volumes/koillection/conf:/conf
            - ./docker/volumes/koillection/uploads:/uploads

    db:
        image: mysql:latest
        container_name: db
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=koillection
            - MYSQL_USER=root
        volumes:
            - "./docker/volumes/mysql:/var/lib/mysql"

```
Unfortunately, when I go to https://IP I get:
SSL_ERROR_RX_RECORD_TOO_LONG
In Edge I get the same error.
May I ask for some assistance here? I am new to the project.

In addition to that I get a warning regarding option being deprecated when performing `docker compose up`:
```
doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
koillection  |
db           | 2023-02-27T17:02:25.747777Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
db           | 2023-02-27T17:02:25.748906Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
```
Also, there is 3rd error I get with this config:
```
koillection  | [27-Feb-2023 17:21:33] NOTICE: PHP message: PHP Warning:  Invalid "apc.shm_size" setting. Invalid quantity "<APC_SHM_SIZE>": no valid leading digits, interpreting as "0" for backwards compatibility in Unknown on line 0
```

**Comment by benjaminjonard** [comment]
Hello,

The Koillection docker container doesn't generate  a SSL certificate by itself. If you need HTTPS and plan to expose Koillection on the internet, I strongly recommend you use a reverse proxy like Traefik or Caddy

Here an exemple using Caddy 

```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  koillection:
    image: koillection/koillection
    container_name: koillection
    restart: unless-stopped
    depends_on:
        - koillection_postgres
    networks:
        - default
        - caddy
    environment:
        ...
        - HTTPS_ENABLED=1
    labels:
        caddy: your_host_here, like an IP a host or localhost
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.header: X-Robots-Tag "noindex, nofollow, nosnippet, noarchive, notranslate, noimageindex"
    volumes:
        - ./volumes/conf:/conf
        - ./volumes/uploads:/upload

  koillection_postgres:
    image: postgres:15
    container_name: koillection_postgres
    restart: unless-stopped
    environment:
        ...
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
        - ./volumes/database:/var/lib/postgresql/data
        
networks:
  caddy:
    external: true
volumes:
  caddy_data: {}
```
